### PR TITLE
ensure subparser is required

### PR DESCRIPTION
**Pull request by ijnek**
When ``bloom-generate`` is called without arguments, this now shows:

```sh
usage: bloom-generate [-h] [debian | rosdebian | rosrpm | rpm] ...
bloom-generate: error: the following arguments are required: [debian | rosdebian | rosrpm | rpm]
```

Rather than continuing without an argument and causing an unrelated error:

```sh
/home/russ/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
/home/russ/.local/lib/python3.10/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Traceback (most recent call last):
  File "/usr/bin/bloom-generate", line 33, in <module>
    sys.exit(load_entry_point('bloom==0.10.7', 'console_scripts', 'bloom-generate')())
  File "/usr/lib/python3/dist-packages/bloom/commands/generate.py", line 85, in main
    handle_global_arguments(args)
  File "/usr/lib/python3/dist-packages/bloom/util.py", line 308, in handle_global_arguments
    enable_debug(args.debug or 'DEBUG' in os.environ)
AttributeError: 'Namespace' object has no attribute 'debug'
```

This fixes the issue #665 is trying to solve.

### CODE REVIEW

**Review by cottsay — APPROVED** [review]

**Comment by christianrauch** [comment]
This breaks bloom on RHEL 8 and clones:
```
  File "/usr/lib64/python3.6/argparse.py", line 1707, in add_subparsers
    action = parsers_class(option_strings=[], **kwargs)
TypeError: __init__() got an unexpected keyword argument 'required'
```

**Comment by ijnek** [comment]
Thanks for the report @christianrauch, I can confirm that the required argument was added in Python3.7

> [required](https://docs.python.org/3.7/library/argparse.html#required) - Whether or not a subcommand must be provided, by default False (added in 3.7) https://docs.python.org/3.7/library/argparse.html#argparse.ArgumentParser.add_subparsers

I have put together a fix: https://github.com/ros-infrastructure/bloom/pull/700

**Comment by cottsay** [comment]
This shouldn't have made it through CI builds if it doesn't work with Python 3.6. We should also investigate that.

**Comment by ijnek** [comment]
I'm not sure which tests were meant to pick up on the problem, but I have confirmed this fixes the immediate problem on RHEL8 in a container. I'd be happy to add a smoke test if there are none for _bloom/commands/generate.py_ yet.
